### ISSUE TITLE
Can't instantiate plugin?

### ISSUE THREAD

**Issue by justinglock40** [levic92/LCExtractor#17]
Any idea what this means and how to fix it?

Traceback (most recent call last):
  File "deluge\pluginmanagerbase.py", line 144, in enable_plugin
  File "c:\config_location\plugins\lcextractor-0.6.2-py2.7.egg\lcextractor\__init__.py", line 44, in __init__
    from core import Core as _plugin_cls
  File "c:\config_location\plugins\lcextractor-0.6.2-py2.7.egg\lcextractor\core.py", line 119, in <module>
NameError: name 'EXTRACT_COMMANDS' is not defined
Unable to instantiate plugin!
name 'EXTRACT_COMMANDS' is not defined

**Comment by justinglock40** [comment]
7-Zip wasn't installed on new windows install.
